//
// Created by anselme on 09/03/2026.
//

#ifndef LEARNOPENGL_TEXTURE_H
#define LEARNOPENGL_TEXTURE_H
#include <string>

/**
 * A texture is a 2D image (even 1D and 3D textures exists) that can be used to add detail to an object.
 * Texture coordinates range from 0 to 1 in x and y-axis.
 * Retrieving the texture color using texture coordinates is called `sampling`.
 *
 */
// y-axis
// ^
// |(0, 1)                              (1, 1)
// |
// |
// |
// |
// |(0, 0) __________________________________> x-axis
class Texture
{
private:
    int Width_{};
    int Height_{};

    /**
     * Path of the texture file from the project root.
     */
    std::string FilePath_;

    /**
     * OpenGL Object ID.
     *
     * This is the unique identifier of the texture in OpenGL context.
     * It is generated by OpenGL when we create a texture and is used to bind the texture to the context and to set its parameters.
     */
    unsigned int ObjectId_{};

public:
    Texture(const std::string &path);

    ~Texture();

    void Bind(unsigned int slot = 0) const;

    void Unbind() const;

    int GetWidth() const { return Width_; }
    int GetHeight() const { return Height_; }
};


#endif //LEARNOPENGL_TEXTURE_H
